name: custom-registry

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Extract package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      
      - name: Set registry prefix
        run: |
          echo "REGISTRY_PREFIX=ghcr.io/${{ github.repository_owner }}/hass-lovelace-kindle-screensaver" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push main image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY_PREFIX }}:${{ env.PACKAGE_VERSION }}
            ${{ env.REGISTRY_PREFIX }}:latest
      
      - name: Build and push HA_Addon AMD64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/amd64-base:latest
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY_PREFIX }}-ha-addon-amd64:${{ env.PACKAGE_VERSION }}
            ${{ env.REGISTRY_PREFIX }}-ha-addon-amd64:latest
      
      - name: Build and push HA_Addon aarch64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/aarch64-base:latest
          platforms: linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY_PREFIX }}-ha-addon-aarch64:${{ env.PACKAGE_VERSION }}
            ${{ env.REGISTRY_PREFIX }}-ha-addon-aarch64:latest
      
      - name: Build and push HA_Addon ARMv7
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/armv7-base:latest
          platforms: linux/arm/v7
          push: true
          tags: |
            ${{ env.REGISTRY_PREFIX }}-ha-addon-armv7:${{ env.PACKAGE_VERSION }}
            ${{ env.REGISTRY_PREFIX }}-ha-addon-armv7:latest
