name: custom-registry

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Extract package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CUSTOM_REGISTRY_URL }}
          username: ${{ secrets.CUSTOM_REGISTRY_USERNAME }}
          password: ${{ secrets.CUSTOM_REGISTRY_TOKEN }}
      
      - name: Build and push main image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ secrets.CUSTOM_REGISTRY_PREFIX }}/hass-lovelace-kindle-screensaver:${{ env.PACKAGE_VERSION }}
            ${{ secrets.CUSTOM_REGISTRY_PREFIX }}/hass-lovelace-kindle-screensaver:latest
      
      - name: Build and push HA_Addon AMD64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/amd64-base:latest
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.CUSTOM_REGISTRY_PREFIX }}/hass-lovelace-kindle-screensaver-ha-addon-amd64:${{ env.PACKAGE_VERSION }}
            ${{ secrets.CUSTOM_REGISTRY_PREFIX }}/hass-lovelace-kindle-screensaver-ha-addon-amd64:latest
      
      - name: Build and push HA_Addon aarch64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/aarch64-base:latest
          platforms: linux/arm64/v8
          push: true
          tags: |
            ${{ secrets.CUSTOM_REGISTRY_PREFIX }}/hass-lovelace-kindle-screensaver-ha-addon-aarch64:${{ env.PACKAGE_VERSION }}
            ${{ secrets.CUSTOM_REGISTRY_PREFIX }}/hass-lovelace-kindle-screensaver-ha-addon-aarch64:latest
      
      - name: Build and push HA_Addon ARMv7
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/armv7-base:latest
          platforms: linux/arm/v7
          push: true
          tags: |
            ${{ secrets.CUSTOM_REGISTRY_PREFIX }}/hass-lovelace-kindle-screensaver-ha-addon-armv7:${{ env.PACKAGE_VERSION }}
            ${{ secrets.CUSTOM_REGISTRY_PREFIX }}/hass-lovelace-kindle-screensaver-ha-addon-armv7:latest
